### ISSUE TITLE
Profiling without Paster?

### ISSUE THREAD

**Issue by ghost** [amcfague/linesman#40]
Is it possible to use linesman without Paster? I'm just using uwsgi and my own wsgi.py without any frameworks. I don't see any uwsgi help options for injecting lineman in.

Not exactly sure how that works. Where would be a good spot for me to learn more?

Thank you!

**Comment by amcfague** [comment]
`linesman` is simply middleware, so it doesn't rely on Paster to run.  You should be able to inject it into any framework; paster is/was the most common way of doing this when it was written.  I'm not especially familiar with uwsgi, but it looks like there is a section that allows you to mimic Paster functionality here: http://uwsgi-docs.readthedocs.io/en/latest/Python.html#paste-support

Otherwise, it's just middleware--you might need to figure out how to integrate it into your application.
